// 单筋矩形截面正截面承载力计算脚本
// Author: Generated by ChatGPT

function formatNumber(value, digits = 3) {
    if (Number.isNaN(value) || !Number.isFinite(value)) {
        return '—';
    }
    return parseFloat(value).toFixed(digits);
}

document.addEventListener('DOMContentLoaded', () => {
    const form = document.getElementById('capacity-form');
    const resultContent = document.getElementById('result-content');

    if (!form || !resultContent) {
        return;
    }

    form.addEventListener('submit', (event) => {
        event.preventDefault();

        const fc = parseFloat(document.getElementById('fc').value);
        const fy = parseFloat(document.getElementById('fy').value);
        const b = parseFloat(document.getElementById('b').value);
        const h = parseFloat(document.getElementById('h').value);
        const cover = parseFloat(document.getElementById('cover').value);
        const areaSteel = parseFloat(document.getElementById('as').value);
        const alpha1 = parseFloat(document.getElementById('alpha1').value);
        const xiLimit = parseFloat(document.getElementById('xiLimit').value);

        const inputs = [fc, fy, b, h, cover, areaSteel, alpha1, xiLimit];
        const hasInvalidInput = inputs.some((value) => Number.isNaN(value) || value <= 0);

        if (hasInvalidInput) {
            resultContent.innerHTML = '<p class="warning">请确保所有输入参数均为正数。</p>';
            return;
        }

        const effectiveDepth = h - cover;

        if (effectiveDepth <= 0) {
            resultContent.innerHTML = '<p class="warning">有效高度 h<sub>0</sub> = h - a<sub>s</sub> 必须大于 0，请检查输入。</p>';
            return;
        }

        const neutralAxisDepth = (areaSteel * fy) / (alpha1 * fc * b);
        const neutralAxisLimit = xiLimit * effectiveDepth;
        const asLimit = (alpha1 * fc * b * neutralAxisLimit) / fy;

        let momentCapacity; // kN·m
        let workingNeutralAxis = neutralAxisDepth;
        let governingMode = '正常受弯，受拉钢筋屈服';
        let remarks = '';

        if (neutralAxisDepth <= neutralAxisLimit) {
            const momentNmm = areaSteel * fy * (effectiveDepth - 0.5 * neutralAxisDepth);
            momentCapacity = momentNmm / 1e6; // 转换为 kN·m
            const reserveSteel = asLimit - areaSteel;
            if (reserveSteel > 0) {
                remarks = `当前受拉钢筋面积低于限值，尚有 ${formatNumber(reserveSteel, 2)} mm² 的增配余量。`;
            }
        } else {
            workingNeutralAxis = neutralAxisLimit;
            const momentNmm = alpha1 * fc * b * workingNeutralAxis * (effectiveDepth - 0.5 * workingNeutralAxis);
            momentCapacity = momentNmm / 1e6;
            governingMode = '超筋破坏，承载力按混凝土压区控制';
            const exceededSteel = areaSteel - asLimit;
            remarks = `受拉钢筋面积超出限值 ${formatNumber(exceededSteel, 2)} mm²，请考虑减少钢筋或增大截面。`;
        }

        const calculationSteps = `
            <ol>
                <li>有效高度：h<sub>0</sub> = h - a<sub>s</sub> = ${h} - ${cover} = <strong>${formatNumber(effectiveDepth, 2)}</strong> mm</li>
                <li>受压区高度：x = A<sub>s</sub>f<sub>y</sub> / (α<sub>1</sub>f<sub>c</sub>b) = ${areaSteel} × ${fy} / (${alpha1} × ${fc} × ${b}) = <strong>${formatNumber(neutralAxisDepth, 2)}</strong> mm</li>
                <li>限值比较：ξ<sub>b</sub>h<sub>0</sub> = ${xiLimit} × ${formatNumber(effectiveDepth, 2)} = <strong>${formatNumber(neutralAxisLimit, 2)}</strong> mm</li>
                <li>判别：x ${neutralAxisDepth <= neutralAxisLimit ? '≤' : '>'} ξ<sub>b</sub>h<sub>0</sub> ⇒ ${governingMode}</li>
                <li>弯矩承载力：M<sub>u</sub> = ${neutralAxisDepth <= neutralAxisLimit ? 'A<sub>s</sub>f<sub>y</sub>(h<sub>0</sub> - 0.5x)' : 'α<sub>1</sub>f<sub>c</sub>bx(h<sub>0</sub> - 0.5x)'} = <strong>${formatNumber(momentCapacity, 3)}</strong> kN·m</li>
            </ol>
        `;

        const reinforcementRatio = areaSteel / (b * effectiveDepth);
        const summaryTable = `
            <table>
                <thead>
                    <tr>
                        <th>参数</th>
                        <th>数值</th>
                        <th>单位</th>
                    </tr>
                </thead>
                <tbody>
                    <tr><td>混凝土抗压强度 f<sub>c</sub></td><td>${formatNumber(fc, 2)}</td><td>MPa</td></tr>
                    <tr><td>钢筋抗拉强度 f<sub>y</sub></td><td>${formatNumber(fy, 2)}</td><td>MPa</td></tr>
                    <tr><td>截面宽度 b</td><td>${formatNumber(b, 2)}</td><td>mm</td></tr>
                    <tr><td>截面高度 h</td><td>${formatNumber(h, 2)}</td><td>mm</td></tr>
                    <tr><td>保护层厚度 a<sub>s</sub></td><td>${formatNumber(cover, 2)}</td><td>mm</td></tr>
                    <tr><td>有效高度 h<sub>0</sub></td><td>${formatNumber(effectiveDepth, 2)}</td><td>mm</td></tr>
                    <tr><td>钢筋面积 A<sub>s</sub></td><td>${formatNumber(areaSteel, 2)}</td><td>mm²</td></tr>
                    <tr><td>受压区高度 x</td><td>${formatNumber(workingNeutralAxis, 2)}</td><td>mm</td></tr>
                    <tr><td>受压区高度限值 ξ<sub>b</sub>h<sub>0</sub></td><td>${formatNumber(neutralAxisLimit, 2)}</td><td>mm</td></tr>
                    <tr><td>钢筋面积限值 A<sub>s,lim</sub></td><td>${formatNumber(asLimit, 2)}</td><td>mm²</td></tr>
                    <tr><td>配筋率 ρ = A<sub>s</sub>/(bh<sub>0</sub>)</td><td>${formatNumber(reinforcementRatio * 100, 3)}</td><td>%</td></tr>
                    <tr><td>弯矩承载力 M<sub>u</sub></td><td>${formatNumber(momentCapacity, 3)}</td><td>kN·m</td></tr>
                </tbody>
            </table>
        `;

        const warningBlock = remarks
            ? `<div class="warning">${remarks}</div>`
            : '';

        resultContent.innerHTML = `
            <div class="highlight"><strong>结论：</strong>${governingMode}，设计弯矩承载力 M<sub>u</sub> = ${formatNumber(momentCapacity, 3)} kN·m。</div>
            ${summaryTable}
            <h3>计算步骤</h3>
            ${calculationSteps}
            ${warningBlock}
        `;
    });

    form.addEventListener('reset', () => {
        window.setTimeout(() => {
            resultContent.innerHTML = '<p>参数已重置，请重新输入并开始计算。</p>';
        }, 0);
    });
});
